[package]
name = "identity-comm"
version = "0.3.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "An implementation of the DIDComm Messaging Specification."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
identity-core = { path = "../identity-core", version = "=0.3.0" }
identity-credential = { path = "../identity-credential", version = "=0.3.0" }
identity-did = { path = "../identity-did", version = "=0.3.0" }
identity-iota = { path = "../identity-iota", version = "=0.3.0" }
libjose = { path = "../libjose", version = "=0.1.0" }
paste = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }
uuid = { version = "0.8", features = ["serde", "v4"], default-features = false }

[features]
# Enables Web Assembly support
wasm = ["uuid/wasm-bindgen"]
