[package]
name = "identity-wasm"
version = "0.3.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Web Assembly bindings for the identity-rs crate."
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity", "wasm"]
homepage = "https://www.iota.org"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1" }
identity = { version = "=0.3.0", path = "../identity", features = ["wasm"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4", default-features = false }

[dependencies.web-sys]
version = "0.3"
default-features = false
features = ["console"]

[dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
getrandom = { version = "0.2", features = ["js"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
